# Generated by Django 5.0.6 on 2024-05-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritor',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='escritor',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='criacao',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='criacao',
        ),
    ]
